---
- hosts: ome
  connection: local
  name: Dell OpenManage Ansible User service.
  gather_facts: False

  collections:
    - dellemc.openmanage
      
  tasks:
  - name: "Create a VLAN range"
    ome_network_vlan:
      hostname: "{{ ome_endpoint }}"
      username: "{{ ome_user }}"
      password: "{{ ome_pass }}"
      state: present
      name: "Ansible-test"
      description: "VLAN desc"
      type: "General Purpose (Bronze)"
      vlan_minimum: 40
      vlan_maximum: 60
    tags: create_vlan
