---
- hosts: ome
  connection: local
  name: Dell OpenManage Ansible User service.
  gather_facts: False
  vars_files:
          - ome-secret.yml

  collections:
    - dellemc.openmanage
      
  tasks:
    - name: changing DNS.
      ome_device_mgmt_network:
        hostname: "{{ ome_endpoint }}"
        username: "{{ ome_user }}"
        password: "{{ ome_pass }}"
        device_service_tag: 7QDS813
        ipv4_configuration:
                enable_ipv4: true
                enable_dhcp: false
                static_ip_address: 192.168.0.2
                static_subnet_mask: 255.255.254.0
                static_gateway: 192.168.0.3
                use_dhcp_to_obtain_dns_server_address: false
                static_preferred_dns_server: 192.168.0.4
                static_alternate_dns_server: 192.168.0.5
