---
- hosts: ome
  connection: local
  name: Dell OpenManage Ansible User service.
  gather_facts: False

  collections:
    - dellemc.openmanage
      
  tasks:
  - name: Create user with required parameters.
    ome_user:
         hostname: "{{ ome_endpoint }}"
         username: "{{ ome_user }}"
         password: "{{ ome_pass }}"
         attributes:
              UserName: "{{ item.UserName }}"
              Password: "{{ item.Password }}"
              RoleId: "{{ item.RoleId }}"
              Enabled: "{{ item.Enabled }}"
    with_items: 
      - "{{ ome_local_user }}" 
