---
- hosts: ome
  connection: local
  name: Dell OpenManage Ansible smart fabric uplink configuration.
  gather_facts: False
  vars_files:
          - ome-secret.yml

  collections:
    - dellemc.openmanage
  

  tasks:
    - name: "Create a smart fabric"
      ome_smart_fabric:
        hostname: "{{ ome_endpoint }}"
        username: "{{ ome_user }}"
        password: "{{ ome_pass }}"
        state: present
        name: "fabric1"
        description: "fabric desc"
        fabric_design: "2xMX9116n_Fabric_Switching_Engines_in_different_chassis"
        primary_switch_service_tag: "DQDS813"
        secondary_switch_service_tag: "GQDS813"
        override_LLDP_configuration: "Enabled"
      tags: create_smart_fabric

  - name: "Create a Uplink"
    ome_smart_fabric_uplink:
      hostname: "{{ ome_endpoint }}"
      username: "{{ ome_user }}"
      password: "{{ ome_pass }}"
      state: "present"
      fabric_name: "MX9116n"
      name: "ansible-uplink"
      description: "CREATED from ansible by elad"
      uplink_type: "Ethernet"
      ufd_enable: "Enabled"
      primary_switch_service_tag: "DQDS813"
      primary_switch_ports:
              - ethernet1/1/41:1
              - ethernet1/1/42:1
      secondary_switch_service_tag: "GQDS813"
      secondary_switch_ports:
              - ethernet1/1/41:1
              - ethernet1/1/42:1
      tagged_networks:
        - VLAN1
      untagged_network: VLAN2
    tags: create_uplink
