---
- hosts: ome
  connection: local
  name: Dell OpenManage Ansible User service.
  gather_facts: False

  collections:
    - dellemc.openmanage
      
  tasks:
  - name: "Delete a VLAN"
    ome_network_vlan:
      hostname: "{{ ome_endpoint }}"
      username: "{{ ome_user }}"
      password: "{{ ome_pass }}"
      state: "absent"
      name: "{{ item.name }}"
    loop: "{{ ome_vlan }}"
    tags: delete_vlan
