---
- hosts: ome
  connection: local
  name: Dell OpenManage Ansible smart fabric uplink configuration.
  gather_facts: False
  vars_files:
          - ome-secret.yml

  collections:
    - dellemc.openmanage
  
  tasks:

    - name: Revert to Hardware Default
      ome_network_port_breakout:
        hostname: "{{ ome_endpoint }}"
        username: "{{ ome_user }}"
        password: "{{ ome_pass }}"
        target_port: "{{ item }}"
        breakout_type: "HardwareDefault"
      loop: "{{ port_groups }}"

    - name: Port breakout configuration.
      ome_network_port_breakout:
        hostname: "{{ ome_endpoint }}"
        username: "{{ ome_user }}"
        password: "{{ ome_pass }}"
        target_port: "{{ item }}"
        breakout_type: "4X10GE"
      loop: "{{ port_groups }}"

      tags:
        - port-config
