---
- hosts: ome
  connection: local
  name: Dell OpenManage Ansible User service.
  gather_facts: False
  vars_files:
          - ome-secret.yml
  collections:
    - dellemc.openmanage
      
  tasks:
  - name: Create user with required parameters.
    ome_user:
         hostname: "{{ ome_endpoint }}"
         username: "{{ ome_user }}"
         password: "{{ ome_pass }}"
         attributes:
              UserName: "Peter"
              Password: "1q2w3e4R%"
              RoleId: "10"
              Enabled: True

