---
- hosts: ome
  connection: local
  name: Dell OpenManage Ansible smart fabric uplink configuration.
  gather_facts: False

  collections:
    - dellemc.openmanage
      
  tasks:
    - name: "Delete a Uplink"
      ome_smart_fabric_uplink:
        hostname: "{{ ome_endpoint }}"
        username: "{{ ome_user }}"
        password: "{{ ome_pass }}"
        state: "absent"
        fabric_name: "MX9116n"
        name: "ansible-uplink"
      tags: delete_uplink
