---
- hosts: ome
  connection: local
  name: Dell OpenManage Ansible User service.
  gather_facts: False

  collections:
    - dellemc.openmanage
      
  tasks:
  - name: "Create a VLAN range"
    ome_network_vlan:
      hostname: "192.168.1.10"
      username: "root"
      password: "Calvin1@"
      state: present
      name: "Ansible-test"
      description: "VLAN desc"
      type: "General Purpose (Bronze)"
      vlan_minimum: 40
      vlan_maximum: 40
    tags: create_vlan
